
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const Terms = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-10">
          <h1 className="text-3xl font-bold">Terms of Service</h1>
        </div>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Usage Terms</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert">
            <p>
              Welcome to Capstone Creator Hub. By using our service, you agree to these terms.
            </p>
            <p>
              The project titles generated by our service are provided for inspiration purposes only. We do not guarantee the originality or academic suitability of any generated titles.
            </p>
            <p>
              You may use the generated titles for your personal academic projects. We encourage you to modify and adapt them to better fit your specific research interests.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Limitations</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert">
            <p>
              Our service is provided "as is" without any warranties, expressed or implied. We do not guarantee continuous, uninterrupted access to our website.
            </p>
            <p>
              We reserve the right to modify or discontinue the service at any time without notice.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Changes to Terms</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert">
            <p>
              We may update these terms from time to time. Any changes will be posted on this page.
            </p>
            <p>
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Terms;
